### ISSUE TITLE
RefreshToken DB에 중복 저장 관련 이슈

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#100]
## Description
RefreshToken이 중복으로 저장돼서 1계정 1토큰으로 리팩토링이 필요해요

## To-do
- [ ] 로그인 시 토큰이 저장되는데 중복으로 저장되고 있어요
- [ ] 로그인 시 리프레시 토큰을 조회해서 없는 경우에만 생성해주고 있을 경우 해당 로직은 통과해줘요
- [ ] 토큰이 만료기간이 되면 업데이트 해주는 API가 필요해요
