### ISSUE TITLE
태그 조회 요청값 변경

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#176]
## Description
태그 조회 시 요청값이 id 에서 nickname으로 변경이 필요해요

## To-do
- [x] 인덱싱을 nickname에 적용해야 해요,
- [x] path variable [id] 에서 [nickname]으로  변경이 필요해요.
- [x] nickname은 중복된 정보가 없어야 해요.
