### ISSUE TITLE
북마크 기능에 유저 정보 값 [NULL]

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#19]
## Description
북마크 및 취소 기능에 유저 정보 값이 없어요.

## To-do
- [x] 유저에 관한 정보가 필요해요.
- [x] 유저에 관한 기능이 생기면 북마크에 user 정보를 저장할거에요.
- [x] url에 북마크 카운트에 user 구분이 생겨서 검증 로직 변경이 필요해요.
