### ISSUE TITLE
로그 기록

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#236]
## Description
로깅을 위해 Spring Interceptor를 사용하면 좋아요

## To-do
- [ ] Interceptor를 사용하여 특정 컨트롤러에 대한 요청 전후의 로깅을 공통 작업으로 처리할 수 있어요
- [ ] 요청 시간과 종료 시간에 대한 로깅도 구현하면 좋아요
- [ ] 코드 중복을 줄여줘요
