### ISSUE TITLE
사용자가 링크를 조회했을 때 읽음 표시 추가

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#70]
## Description
사용자가 링크를 조회했을 때 읽은적이 있다는 걸 확인하면 좋을 것 같아요!

## To-do
- [x] 로그인 한 유저의 id 와 link의 id를 가지고 읽음 여부에 대한 디비 스키마를 만들어주면 될 것 같아요
- [x] 링크 클릭 시 읽음 여부에 대한 디비 스키마에 적재돼요
- [x] 링크 리스트 조회할 때 읽음에 대한 스키마도 조회해서 존재한다면 true 없다면 false로 판단해주면 될 것 같아요
- [x] 더 좋은 의견 있으면 부탁드릴게요

**Comment by esubine** [comment]
읽음여부 true/false 좋은거같습니다!
