### ISSUE TITLE
첫 로그인인지 확인하는 기능이 필요해요..!

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#81]
## Description
첫 로그인이 맞는지 확인하는 기능이 필요해요..

## To-do
- [ ] 닉네임이라는 유니크한 정보가 필요해서 기능을 추가해야 해요..
- [ ] 첫 카카오 로그인 시 닉네임 디폴트를 "" 빈 배열로 만들어줬어요
- [ ] 닉네임이 디폴트 "" 인 유저는 첫 로그인 유저로 판단해요!
