### ISSUE TITLE
회원 정보 수정 API 시 500에러에 대한 예외처리

### ISSUE THREAD

**Issue by taegyun1995** [linkarchive/Back-End#83]
## Description
회원 정보 수정 시 500에러에 대한 예외처리가 필요해요

## To-do
- [ ] 400 , 500 에러에 대한 학습이 필요할 것 같아요
- [ ] 500 예외처리는 서버 에러쪽이라서 커스텀할 때 방식이 좀 다른것 같아요 학습이 필요합니다..
- [ ] 3개의 request 가 있는데 하나만 보내줘도 수정 API가 되게끔 리팩토링이 필요할 것 같아요
